Repository TheIllusiveC4/Champions, pull requests merged in 2022-04, with the labels that each got.

#114 Champion killed by player advancement trigger
  .editorconfig
  .gitignore
  build.gradle
  src/main/java/top/theillusivec4/champions/Champions.java
  src/main/java/top/theillusivec4/champions/common/ChampionEventsHandler.java
  src/main/java/top/theillusivec4/champions/server/advancement/ChampionsCriterionTriggers.java
  src/main/java/top/theillusivec4/champions/server/advancement/criterion/ChampionKilledByPlayerTrigger.java
Labels: enhancement

#115 Add Support for The One Probe
  build.gradle
  gradle.properties
  src/main/java/top/theillusivec4/champions/Champions.java
  src/main/java/top/theillusivec4/champions/common/integration/theoneprobe/TheOneProbePlugin.java
Labels: enhancement

#116 Update ko_kr.json
  src/main/resources/assets/champions/lang/ko_kr.json
Labels: localization

#117 Update ko_kr.json
  src/main/resources/assets/champions/lang/ko_kr.json
Labels: bug

#118 Update Simplified Chinese translation
  src/main/resources/assets/champions/lang/zh_cn.json
Labels: localization
